# Generated by Django 5.2.14 on 2026-07-06 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('psi_mi_code', models.CharField(blank=True, default='', max_length=30)),
                ('quality_score', models.FloatField(blank=True, help_text='Weight in HIPPIE confidence scoring', null=True)),
            ],
            options={
                'db_table': 'experiment_type',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrez_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('entrez_name', models.CharField(blank=True, db_index=True, default='', max_length=40)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('psi_mi_code', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'db_table': 'interaction_type',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_accession', models.CharField(db_index=True, max_length=20, unique=True)),
                ('uniprot_name', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('degree', models.PositiveIntegerField(db_index=True, default=0)),
                ('avg_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='hippie_website.gene')),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.PositiveBigIntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('version_label', models.CharField(blank=True, default='', max_length=32)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('int_q1', models.FloatField(blank=True, null=True)),
                ('int_median', models.FloatField(blank=True, null=True)),
                ('int_q3', models.FloatField(blank=True, null=True)),
                ('nonint_q1', models.FloatField(blank=True, null=True)),
                ('nonint_median', models.FloatField(blank=True, null=True)),
                ('nonint_q3', models.FloatField(blank=True, null=True)),
                ('both_q1', models.FloatField(blank=True, null=True)),
                ('both_median', models.FloatField(blank=True, null=True)),
                ('both_q3', models.FloatField(blank=True, null=True)),
                ('resource_versions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'release_meta',
                'ordering': ['-release_date', '-release_number'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, default='')),
                ('n_connected_interactions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('NCBI_tax_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tissue',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True)),
                ('involves_isoform', models.BooleanField(db_index=True, default=False)),
                ('n_sources', models.PositiveIntegerField(default=0)),
                ('n_experiments', models.PositiveIntegerField(default=0)),
                ('experiments', models.ManyToManyField(db_table='interaction2experiment', related_name='interactions', to='hippie_website.experimenttype')),
                ('interaction_types', models.ManyToManyField(db_table='interaction2type', related_name='interactions', to='hippie_website.interactiontype')),
                ('protein_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_1', to='hippie_website.protein')),
                ('protein_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_2', to='hippie_website.protein')),
                ('publications', models.ManyToManyField(db_table='interaction2pubmed', related_name='interactions', to='hippie_website.publication')),
                ('sources', models.ManyToManyField(db_table='interaction2source', related_name='interactions', to='hippie_website.source')),
                ('conserved_species', models.ManyToManyField(db_table='interaction2species', related_name='conserved_interactions', to='hippie_website.species')),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
        migrations.CreateModel(
            name='NonInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True)),
                ('protein_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noninteractions_as_1', to='hippie_website.protein')),
                ('protein_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noninteractions_as_2', to='hippie_website.protein')),
            ],
            options={
                'db_table': 'noninteraction',
            },
        ),
        migrations.CreateModel(
            name='ProteinSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(db_index=True, help_text='Alternative name or identifier for the protein', max_length=60)),
                ('additional_information', models.CharField(blank=True, max_length=255, null=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='hippie_website.protein')),
            ],
            options={
                'db_table': 'protein_synonym',
            },
        ),
        migrations.CreateModel(
            name='BaitPreyAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_observed', models.PositiveIntegerField(default=0)),
                ('number_of_tests', models.PositiveIntegerField(default=0)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bait_prey', to='hippie_website.interaction')),
                ('noninteraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bait_prey', to='hippie_website.noninteraction')),
                ('publications', models.ManyToManyField(db_table='bait_prey_assoc2publication', related_name='bait_prey_associations', to='hippie_website.publication')),
            ],
            options={
                'db_table': 'bait_prey_assoc',
            },
        ),
        migrations.CreateModel(
            name='OrthologInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortholog_interactions_as_1', to='hippie_website.gene')),
                ('gene_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortholog_interactions_as_2', to='hippie_website.gene')),
                ('ortholog_species', models.ManyToManyField(db_table='ortholog_interaction_species', related_name='ortholog_interactions', to='hippie_website.species')),
            ],
            options={
                'db_table': 'ortholog_interaction',
            },
        ),
        migrations.CreateModel(
            name='InteractionCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(help_text='e.g. "MINT-10096"', max_length=40)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='hippie_website.interaction')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='hippie_website.source')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='hippie_website.species')),
            ],
            options={
                'db_table': 'interaction2link',
            },
        ),
        migrations.CreateModel(
            name='SplitJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('params', models.JSONField()),
                ('progress', models.FloatField(default=0.0)),
                ('step', models.CharField(blank=True, max_length=40)),
                ('zip_path', models.CharField(blank=True, max_length=512)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='splitjob_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneTissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_rpkm', models.FloatField(verbose_name='rpkm')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tissue_expression', to='hippie_website.gene')),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressed_genes', to='hippie_website.tissue')),
            ],
            options={
                'db_table': 'gene2tissue',
            },
        ),
        migrations.CreateModel(
            name='GeneSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(db_index=True, help_text='Alternative name or symbol for the gene', max_length=60)),
                ('additional_information', models.CharField(blank=True, max_length=255, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='hippie_website.gene')),
            ],
            options={
                'db_table': 'gene_synonym',
                'constraints': [models.UniqueConstraint(fields=('gene', 'synonym'), name='unique_gene_synonym')],
            },
        ),
        migrations.CreateModel(
            name='Isoform',
            fields=[
                ('protein_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hippie_website.protein')),
                ('general_protein', models.ForeignKey(help_text='Canonical parent protein for this isoform', on_delete=django.db.models.deletion.CASCADE, related_name='isoforms', to='hippie_website.protein')),
            ],
            options={
                'db_table': 'isoform',
            },
            bases=('hippie_website.protein',),
        ),
        migrations.AddIndex(
            model_name='noninteraction',
            index=models.Index(fields=['protein_1', 'score'], name='noninteract_protein_e7033e_idx'),
        ),
        migrations.AddIndex(
            model_name='noninteraction',
            index=models.Index(fields=['protein_2', 'score'], name='noninteract_protein_522922_idx'),
        ),
        migrations.AddIndex(
            model_name='noninteraction',
            index=models.Index(fields=['score', 'id'], name='noninteract_score_d3d6d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='noninteraction',
            constraint=models.CheckConstraint(condition=models.Q(('protein_1_id__lte', models.F('protein_2_id'))), name='noninteraction_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='noninteraction',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='noninteraction_score_range'),
        ),
        migrations.AddConstraint(
            model_name='noninteraction',
            constraint=models.UniqueConstraint(fields=('protein_1', 'protein_2'), name='noninteraction_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='proteinsynonym',
            constraint=models.UniqueConstraint(fields=('protein', 'synonym'), name='unique_protein_synonym'),
        ),
        migrations.AddConstraint(
            model_name='baitpreyassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('interaction__isnull', False)), fields=('interaction',), name='bait_prey_unique_interaction'),
        ),
        migrations.AddConstraint(
            model_name='baitpreyassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('noninteraction__isnull', False)), fields=('noninteraction',), name='bait_prey_unique_noninteraction'),
        ),
        migrations.AddConstraint(
            model_name='baitpreyassociation',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__isnull', True), ('noninteraction__isnull', True), _connector='OR'), name='max_one_link_to_interaction_or_noninteraction'),
        ),
        migrations.AddIndex(
            model_name='orthologinteraction',
            index=models.Index(fields=['gene_1', 'gene_2'], name='ortholog_in_gene_1__4d6536_idx'),
        ),
        migrations.AddConstraint(
            model_name='orthologinteraction',
            constraint=models.CheckConstraint(condition=models.Q(('gene_1_id__lte', models.F('gene_2_id'))), name='ortholog_interaction_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='orthologinteraction',
            constraint=models.UniqueConstraint(fields=('gene_1', 'gene_2'), name='ortholog_interaction_unique'),
        ),
        migrations.AddIndex(
            model_name='interactioncrossreference',
            index=models.Index(fields=['interaction', 'source'], name='interaction_interac_2dfcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['protein_1', 'score'], name='interaction_protein_105d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['protein_2', 'score'], name='interaction_protein_f2683f_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['score', 'id'], name='interaction_score_ad1a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['n_sources', 'id'], name='interaction_n_sourc_83710f_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['n_experiments', 'id'], name='interaction_n_exper_4b12d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('protein_1_id__lte', models.F('protein_2_id'))), name='interaction_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='interaction_score_range'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('protein_1', 'protein_2'), name='interaction_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='genetissue',
            constraint=models.UniqueConstraint(fields=('gene', 'tissue'), name='gene_tissue_unique'),
        ),
    ]
