# Generated by Django 6.0.3 on 2026-04-17 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('params', models.JSONField()),
                ('progress', models.FloatField(default=0.0)),
                ('step', models.CharField(blank=True, max_length=40)),
                ('zip_path', models.CharField(blank=True, max_length=512)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
