# Generated by Django 6.0.3 on 2026-06-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orthologinteraction',
            name='ortholog_interaction_canonical_order',
        ),
        migrations.RemoveConstraint(
            model_name='orthologinteraction',
            name='ortholog_interaction_unique',
        ),
        migrations.RemoveIndex(
            model_name='orthologinteraction',
            name='ortholog_in_protein_aaa791_idx',
        ),
        migrations.AddField(
            model_name='orthologinteraction',
            name='gene_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ortholog_interactions_as_1', to='hippie_website.gene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orthologinteraction',
            name='gene_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ortholog_interactions_as_2', to='hippie_website.gene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='NCBI_tax_id',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='orthologinteraction',
            index=models.Index(fields=['gene_1', 'gene_2'], name='ortholog_in_gene_1__4d6536_idx'),
        ),
        migrations.AddConstraint(
            model_name='orthologinteraction',
            constraint=models.CheckConstraint(condition=models.Q(('gene_1_id__lte', models.F('gene_2_id'))), name='ortholog_interaction_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='orthologinteraction',
            constraint=models.UniqueConstraint(fields=('gene_1', 'gene_2'), name='ortholog_interaction_unique'),
        ),
        migrations.RemoveField(
            model_name='orthologinteraction',
            name='protein_1',
        ),
        migrations.RemoveField(
            model_name='orthologinteraction',
            name='protein_2',
        ),
        migrations.RemoveField(
            model_name='orthologinteraction',
            name='source',
        ),
    ]
