# Generated by Django 5.2.14 on 2026-06-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippie_website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="experimenttype",
            name="experiment_type_psi_mi_unique",
        ),
        migrations.RemoveConstraint(
            model_name="interactiontype",
            name="interaction_type_psi_mi_unique",
        ),
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
