# Generated by Django 6.0.3 on 2026-04-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baitpreyassociation',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bait_prey', to='hippie_website.interaction'),
        ),
        migrations.CreateModel(
            name='NonInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True)),
                ('protein_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noninteractions_as_1', to='hippie_website.protein')),
                ('protein_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noninteractions_as_2', to='hippie_website.protein')),
            ],
            options={
                'db_table': 'noninteraction',
            },
        ),
        migrations.AddField(
            model_name='baitpreyassociation',
            name='noninteraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bait_prey', to='hippie_website.noninteraction'),
        ),
        migrations.AddConstraint(
            model_name='baitpreyassociation',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__isnull', True), ('direction__isnull', True), _connector='OR'), name='one_link_to_interaction_or_noninteraction'),
        ),
        migrations.AddIndex(
            model_name='noninteraction',
            index=models.Index(fields=['protein_1', 'score'], name='noninteract_protein_e7033e_idx'),
        ),
        migrations.AddIndex(
            model_name='noninteraction',
            index=models.Index(fields=['protein_2', 'score'], name='noninteract_protein_522922_idx'),
        ),
        migrations.AddConstraint(
            model_name='noninteraction',
            constraint=models.CheckConstraint(condition=models.Q(('protein_1_id__lte', models.F('protein_2_id'))), name='noninteraction_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='noninteraction',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='noninteraction_score_range'),
        ),
        migrations.AddConstraint(
            model_name='noninteraction',
            constraint=models.UniqueConstraint(fields=('protein_1', 'protein_2'), name='noninteraction_unique_pair'),
        ),
    ]
