# Generated by Django 6.0.3 on 2026-05-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippie_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="avg_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="protein",
            name="degree",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
