# Generated by Django 5.2.14 on 2026-07-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='conserved_species',
        ),
    ]
