# Generated by Django 5.2.14 on 2026-07-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0002_remove_interaction_conserved_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='ensg',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='isoform',
            name='ensp',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='isoform',
            name='enst',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
