# Generated by Django 6.0.3 on 2026-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hippie_website",
            "0002_remove_baitpreyassociation_max_one_link_to_interaction_or_noninteraction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="baitpreytest",
            name="bait_prey_test_unique",
        ),
        migrations.AddConstraint(
            model_name="baitpreytest",
            constraint=models.UniqueConstraint(
                fields=("detection", "pmid", "method"), name="bait_prey_test_unique"
            ),
        ),
    ]
