# Generated by Django 5.2.14 on 2026-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0003_gene_ensg_isoform_ensp_isoform_enst'),
    ]

    operations = [
        migrations.AddField(
            model_name='isoform',
            name='is_canonical',
            field=models.BooleanField(default=False, help_text="True when this isoform's sequence (UniParc) equals its parent protein's canonical sequence."),
        ),
    ]
