# Generated by Django 6.0.3 on 2026-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippie_website", "0004_remove_baitpreytest_bait_prey_test_unique_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="baitpreyassociation",
            name="bait_pray_unique",
        ),
        migrations.AddConstraint(
            model_name="baitpreyassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("interaction__isnull", False)),
                fields=("interaction",),
                name="bait_prey_unique_interaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="baitpreyassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("noninteraction__isnull", False)),
                fields=("noninteraction",),
                name="bait_prey_unique_noninteraction",
            ),
        ),
        migrations.RemoveField(
            model_name="baitpreyassociation",
            name="direction",
        ),
    ]
