# Generated by Django 5.2.14 on 2026-07-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0004_isoform_is_canonical'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimenttype',
            name='n_connected_interactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='n_connected_interactions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
