# Generated by Django 5.2.14 on 2026-07-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippie_website", "0005_remove_baitpreyassociation_bait_pray_unique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "release_number",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "version_label",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("int_q1", models.FloatField(blank=True, null=True)),
                ("int_median", models.FloatField(blank=True, null=True)),
                ("int_q3", models.FloatField(blank=True, null=True)),
                ("nonint_q1", models.FloatField(blank=True, null=True)),
                ("nonint_median", models.FloatField(blank=True, null=True)),
                ("nonint_q3", models.FloatField(blank=True, null=True)),
                ("both_q1", models.FloatField(blank=True, null=True)),
                ("both_median", models.FloatField(blank=True, null=True)),
                ("both_q3", models.FloatField(blank=True, null=True)),
                ("resource_versions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "release_meta",
                "ordering": ["-release_date", "-release_number"],
            },
        ),
        migrations.AddField(
            model_name="protein",
            name="is_swissprot",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
