# Generated by Django 6.0.3 on 2026-07-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippie_website", "0005_remove_baitpreyassociation_bait_pray_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="is_reviewed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
