# Generated by Django 5.2.14 on 2026-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_website', '0005_experimenttype_n_connected_interactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='n_expressed_genes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
