# Generated by Django 5.2.14 on 2026-09-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hippie_website", "0006_tissue_n_expressed_genes"),
    ]

    operations = [
        migrations.AddField(
            model_name="splitjob",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="splitjob",
            name="nf_run_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="splitjob",
            name="outdir",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="splitjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="splitjob",
            name="work_dir",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="splitjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
