# Generated by Django 5.2.14 on 2026-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hippie_website",
            "0007_splitjob_cancel_requested_splitjob_nf_run_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="splitjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
