# Generated by Django 5.2.14 on 2026-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippie_website", "0010_add_evidence_count_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="splitjob",
            index=models.Index(
                fields=["status", "created_at"], name="splitjob_status_created_idx"
            ),
        ),
    ]
