"""
Django settings for hippie project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-3wq+cj5bp*g)wk1ql%%#%ybb^u=cac5^zg0cv_*if4w!+ff*tn",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    h.strip()
    for h in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "hippie_website.apps.HippieWebsiteConfig",
    "django_vite",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hippie.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "hippie_website.context_processors.release",
            ],
        },
    },
]

WSGI_APPLICATION = "hippie.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("DATABASE_ENGINE") == "mariadb":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["MARIADB_DATABASE"],
            "USER": os.environ["MARIADB_USER"],
            "PASSWORD": os.environ["MARIADB_PASSWORD"],
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {"charset": "utf8mb4"},
            # Reuse connections across requests (avoid per-request connect/auth).
            "CONN_MAX_AGE": 60,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use DJANGO_STATIC_URL, if empty use APACHE_PUBLISHED_PATH, if empty use "" (no prefix)
STATIC_URL = (
    os.environ.get("DJANGO_STATIC_URL") or os.environ.get("APACHE_PUBLISHED_PATH", "")
).rstrip("/") + "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use DJANGO_SCRIPT_NAME, if empty use APACHE_PUBLISHED_PATH, if empty use "" (no prefix)
FORCE_SCRIPT_NAME = (
    os.environ.get("DJANGO_SCRIPT_NAME") or os.environ.get("APACHE_PUBLISHED_PATH", "")
).rstrip("/")

DJANGO_VITE = {
    "default": {
        "dev_mode": False,
        "manifest_path": BASE_DIR
        / "hippie_website/static/hippie_website/js/.vite/manifest.json",
        "static_url_prefix": "hippie_website/js",
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Media files (split zips) ───────────────────────────────────────────────
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# ── Celery ─────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", "redis://localhost:6379/0"
)
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
# Uncomment to run tasks synchronously (no Redis required for dev/testing):
# CELERY_TASK_ALWAYS_EAGER = True

# ── Cache ──────────────────────────────────────────────────────────────────
# Used to memoise the browse-page row counts so pagination and repeat loads
# don't re-COUNT the 1.15M-row interaction table. When REDIS_CACHE_URL is set
# (prod), use the django 5.2 built-in Redis backend (no django-redis dep —
# relies on the already-installed `redis` package) on a separate DB index (/1)
# from Celery (/0). Otherwise fall back to per-process local memory so dev and
# the test suite need no running Redis. Mirrors the mariadb/sqlite switch above.
if os.environ.get("REDIS_CACHE_URL"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.environ["REDIS_CACHE_URL"],
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
